/* ============================================================
   QuizVerse — Built-in offline question bank
   Format: [question, correctAnswer, wrong1, wrong2, wrong3]
   Each category has easy / medium / hard pools.
   ============================================================ */

const QUESTION_BANK = {
  general: {
    name: "General Knowledge",
    icon: "🌍",
    easy: [
      ["How many continents are there on Earth?", "7", "5", "6", "8"],
      ["What is the largest ocean on Earth?", "Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"],
      ["How many colors are in a rainbow?", "7", "5", "6", "8"],
      ["Which planet is known as the Red Planet?", "Mars", "Venus", "Jupiter", "Mercury"],
      ["What is the tallest animal in the world?", "Giraffe", "Elephant", "Ostrich", "Camel"],
      ["How many days are there in a leap year?", "366", "365", "364", "367"],
      ["What do bees collect from flowers?", "Nectar", "Water", "Seeds", "Leaves"],
      ["Which is the largest mammal on Earth?", "Blue whale", "African elephant", "Giraffe", "Hippopotamus"],
    ],
    medium: [
      ["What is the currency of Japan?", "Yen", "Won", "Yuan", "Ringgit"],
      ["Which gas makes up most of Earth's atmosphere?", "Nitrogen", "Oxygen", "Carbon dioxide", "Argon"],
      ["What is the smallest country in the world?", "Vatican City", "Monaco", "San Marino", "Liechtenstein"],
      ["How many bones does an adult human body have?", "206", "196", "216", "226"],
      ["Which language has the most native speakers worldwide?", "Mandarin Chinese", "English", "Spanish", "Hindi"],
      ["What is the national flower of Japan?", "Cherry blossom", "Lotus", "Rose", "Chrysanthemum"],
      ["Which organ in the human body produces insulin?", "Pancreas", "Liver", "Kidney", "Spleen"],
      ["What is the longest river in the world by most measures?", "Nile", "Amazon", "Yangtze", "Mississippi"],
    ],
    hard: [
      ["What is the only letter that does not appear in any U.S. state name?", "Q", "Z", "X", "J"],
      ["Which country has the most time zones, including territories?", "France", "Russia", "USA", "China"],
      ["What is the collective noun for a group of crows?", "A murder", "A parliament", "A gaggle", "A pride"],
      ["The unit 'candela' measures what physical quantity?", "Luminous intensity", "Sound intensity", "Pressure", "Radioactivity"],
      ["Which vitamin is also known as ascorbic acid?", "Vitamin C", "Vitamin A", "Vitamin B12", "Vitamin D"],
      ["In which city is the world's oldest continuously operating university, founded in 859 AD?", "Fez, Morocco", "Bologna, Italy", "Oxford, England", "Cairo, Egypt"],
      ["What is the fear of long words humorously called?", "Hippopotomonstrosesquippedaliophobia", "Logophobia", "Verbophobia", "Lexicophobia"],
      ["Which metal is liquid at room temperature besides mercury?", "Gallium (near room temp)", "Sodium", "Aluminium", "Zinc"],
    ],
  },

  science: {
    name: "Science & Nature",
    icon: "🔬",
    easy: [
      ["What is H2O commonly known as?", "Water", "Salt", "Oxygen", "Hydrogen peroxide"],
      ["Which planet is closest to the Sun?", "Mercury", "Venus", "Mars", "Earth"],
      ["What force pulls objects toward the Earth?", "Gravity", "Magnetism", "Friction", "Inertia"],
      ["What do plants absorb from the air for photosynthesis?", "Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"],
      ["How many legs does a spider have?", "8", "6", "10", "12"],
      ["What is the center of an atom called?", "Nucleus", "Electron", "Proton cloud", "Shell"],
      ["Which organ pumps blood around the human body?", "Heart", "Lungs", "Brain", "Liver"],
      ["What is the process by which water turns into vapor?", "Evaporation", "Condensation", "Precipitation", "Sublimation"],
    ],
    medium: [
      ["What is the chemical symbol for gold?", "Au", "Ag", "Gd", "Go"],
      ["What type of blood cells fight infection?", "White blood cells", "Red blood cells", "Platelets", "Plasma cells"],
      ["What is the speed of light in a vacuum, approximately?", "300,000 km/s", "150,000 km/s", "1,000,000 km/s", "30,000 km/s"],
      ["Which gas do plants release during photosynthesis?", "Oxygen", "Carbon dioxide", "Nitrogen", "Methane"],
      ["What is the hardest natural substance on Earth?", "Diamond", "Quartz", "Titanium", "Graphite"],
      ["What part of the cell contains genetic material?", "Nucleus", "Mitochondria", "Ribosome", "Cytoplasm"],
      ["What is the study of earthquakes called?", "Seismology", "Geology", "Meteorology", "Volcanology"],
      ["Which element has the atomic number 1?", "Hydrogen", "Helium", "Oxygen", "Carbon"],
    ],
    hard: [
      ["What is the most abundant element in the universe?", "Hydrogen", "Helium", "Oxygen", "Carbon"],
      ["Which scientist proposed the theory of general relativity?", "Albert Einstein", "Isaac Newton", "Niels Bohr", "Max Planck"],
      ["What is the powerhouse of the cell?", "Mitochondria", "Nucleus", "Golgi apparatus", "Lysosome"],
      ["What particle is exchanged in electromagnetic interactions?", "Photon", "Gluon", "W boson", "Graviton"],
      ["What is the half-life of Carbon-14, used in radiocarbon dating?", "About 5,730 years", "About 1,000 years", "About 50,000 years", "About 500 years"],
      ["Which blood type is the universal donor?", "O negative", "AB positive", "A positive", "B negative"],
      ["What does DNA stand for?", "Deoxyribonucleic acid", "Dinucleic acid", "Deoxyribose nitric acid", "Dual ribonucleic acid"],
      ["Which planet has the shortest day in the Solar System?", "Jupiter", "Mercury", "Mars", "Neptune"],
    ],
  },

  history: {
    name: "History",
    icon: "🏛️",
    easy: [
      ["Who was the first President of the United States?", "George Washington", "Abraham Lincoln", "Thomas Jefferson", "John Adams"],
      ["The Great Wall is located in which country?", "China", "Japan", "India", "Mongolia"],
      ["Which ship sank in 1912 after hitting an iceberg?", "Titanic", "Lusitania", "Britannic", "Queen Mary"],
      ["The pyramids of Giza are in which country?", "Egypt", "Mexico", "Peru", "Sudan"],
      ["Who discovered America in 1492 (for Europe)?", "Christopher Columbus", "Vasco da Gama", "Ferdinand Magellan", "Marco Polo"],
      ["In which year did World War II end?", "1945", "1939", "1944", "1950"],
      ["Who was known as the 'Iron Lady'?", "Margaret Thatcher", "Indira Gandhi", "Angela Merkel", "Golda Meir"],
      ["Which ancient civilization built Machu Picchu?", "Inca", "Aztec", "Maya", "Olmec"],
    ],
    medium: [
      ["Who was the first man to step on the Moon?", "Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Michael Collins"],
      ["The French Revolution began in which year?", "1789", "1776", "1799", "1804"],
      ["Which empire was ruled by Julius Caesar?", "Roman Empire", "Greek Empire", "Ottoman Empire", "Persian Empire"],
      ["The Berlin Wall fell in which year?", "1989", "1991", "1985", "1979"],
      ["Who wrote the 95 Theses, sparking the Reformation?", "Martin Luther", "John Calvin", "Henry VIII", "Erasmus"],
      ["Which country gifted the Statue of Liberty to the USA?", "France", "England", "Spain", "Italy"],
      ["Who was the Egyptian queen romantically linked to Julius Caesar and Mark Antony?", "Cleopatra", "Nefertiti", "Hatshepsut", "Isis"],
      ["The Cold War was primarily between the USA and which country?", "Soviet Union", "China", "Germany", "Japan"],
    ],
    hard: [
      ["The Treaty of Westphalia (1648) ended which conflict?", "Thirty Years' War", "Hundred Years' War", "War of Spanish Succession", "Napoleonic Wars"],
      ["Who was the last Tsar of Russia?", "Nicholas II", "Alexander III", "Peter III", "Ivan VI"],
      ["Which battle in 1815 marked Napoleon's final defeat?", "Battle of Waterloo", "Battle of Trafalgar", "Battle of Austerlitz", "Battle of Leipzig"],
      ["The Rosetta Stone helped decipher which script?", "Egyptian hieroglyphs", "Cuneiform", "Linear B", "Sanskrit"],
      ["Which dynasty built the Forbidden City in Beijing?", "Ming", "Qing", "Han", "Tang"],
      ["Who was the first emperor of unified China?", "Qin Shi Huang", "Kublai Khan", "Sun Yat-sen", "Wu Zetian"],
      ["In which year did the Byzantine Empire fall to the Ottomans?", "1453", "1492", "1389", "1517"],
      ["The Magna Carta was signed by which English king?", "King John", "Henry VIII", "Richard I", "Edward I"],
    ],
  },

  geography: {
    name: "Geography",
    icon: "🗺️",
    easy: [
      ["What is the capital of France?", "Paris", "Lyon", "Marseille", "Nice"],
      ["Which is the largest desert in the world?", "Antarctic Desert", "Sahara", "Gobi", "Arabian"],
      ["Mount Everest is in which mountain range?", "Himalayas", "Andes", "Alps", "Rockies"],
      ["Which country is shaped like a boot?", "Italy", "Spain", "Portugal", "Greece"],
      ["What is the capital of Japan?", "Tokyo", "Osaka", "Kyoto", "Nagoya"],
      ["The Amazon rainforest is mostly in which country?", "Brazil", "Peru", "Colombia", "Venezuela"],
      ["Which continent is the coldest?", "Antarctica", "Europe", "North America", "Asia"],
      ["What is the capital of Australia?", "Canberra", "Sydney", "Melbourne", "Perth"],
    ],
    medium: [
      ["Which two countries share the longest international border?", "USA and Canada", "Russia and China", "Argentina and Chile", "India and China"],
      ["The Strait of Gibraltar separates Spain from which country?", "Morocco", "Algeria", "Tunisia", "Portugal"],
      ["Which river flows through Egypt?", "Nile", "Tigris", "Euphrates", "Jordan"],
      ["What is the capital of Canada?", "Ottawa", "Toronto", "Vancouver", "Montreal"],
      ["Which country has the most islands in the world?", "Sweden", "Indonesia", "Philippines", "Norway"],
      ["Lake Baikal, the world's deepest lake, is in which country?", "Russia", "Mongolia", "Kazakhstan", "China"],
      ["Which African country was formerly called Abyssinia?", "Ethiopia", "Eritrea", "Somalia", "Sudan"],
      ["The Andes mountains run along which coast of South America?", "West", "East", "North", "South"],
    ],
    hard: [
      ["Which is the only country that borders both the Atlantic and Indian Oceans in Africa?", "South Africa", "Namibia", "Mozambique", "Angola"],
      ["What is the capital of Kazakhstan?", "Astana", "Almaty", "Tashkent", "Bishkek"],
      ["Which country is completely surrounded by South Africa?", "Lesotho", "Eswatini", "Botswana", "Malawi"],
      ["The Atacama Desert is located in which country?", "Chile", "Peru", "Bolivia", "Argentina"],
      ["Which sea is the saltiest natural body of water in the world?", "Dead Sea", "Red Sea", "Caspian Sea", "Great Salt Lake"],
      ["What is the only continent without a desert?", "Europe", "South America", "Australia", "North America"],
      ["Which country has three capital cities?", "South Africa", "Bolivia", "Netherlands", "Malaysia"],
      ["The Danube River empties into which sea?", "Black Sea", "Mediterranean Sea", "Baltic Sea", "Adriatic Sea"],
    ],
  },

  sports: {
    name: "Sports",
    icon: "🏆",
    easy: [
      ["How many players are on a soccer (football) team on the field?", "11", "9", "10", "12"],
      ["In which sport would you perform a slam dunk?", "Basketball", "Volleyball", "Tennis", "Badminton"],
      ["How often are the Summer Olympic Games held?", "Every 4 years", "Every 2 years", "Every 3 years", "Every 5 years"],
      ["Which sport uses a shuttlecock?", "Badminton", "Tennis", "Squash", "Table tennis"],
      ["What color jersey does the Tour de France leader wear?", "Yellow", "Green", "White", "Red"],
      ["In cricket, how many runs is a boundary hit along the ground worth?", "4", "6", "2", "1"],
      ["Which country hosts the Wimbledon tennis tournament?", "England", "France", "USA", "Australia"],
      ["How many rings are on the Olympic flag?", "5", "4", "6", "7"],
    ],
    medium: [
      ["Which country won the first FIFA World Cup in 1930?", "Uruguay", "Brazil", "Argentina", "Italy"],
      ["In basketball, how many points is a free throw worth?", "1", "2", "3", "4"],
      ["Who holds the record for most Grand Slam singles titles in men's tennis (as of 2024)?", "Novak Djokovic", "Rafael Nadal", "Roger Federer", "Pete Sampras"],
      ["What is the maximum break in snooker?", "147", "155", "140", "150"],
      ["Which boxer was known as 'The Greatest'?", "Muhammad Ali", "Mike Tyson", "Joe Frazier", "George Foreman"],
      ["In which sport is the Ryder Cup contested?", "Golf", "Tennis", "Sailing", "Rowing"],
      ["Usain Bolt set the 100m world record with what time?", "9.58 seconds", "9.69 seconds", "9.72 seconds", "9.49 seconds"],
      ["Which country has won the most Cricket World Cups (ODI, men's)?", "Australia", "India", "West Indies", "England"],
    ],
    hard: [
      ["Which city hosted the first modern Olympic Games in 1896?", "Athens", "Paris", "London", "Rome"],
      ["In fencing, what is the lightest of the three weapons?", "Foil", "Épée", "Sabre", "Rapier"],
      ["Who scored the 'Hand of God' goal in the 1986 World Cup?", "Diego Maradona", "Pelé", "Michel Platini", "Gary Lineker"],
      ["What is the diameter of a basketball hoop in inches?", "18 inches", "16 inches", "20 inches", "22 inches"],
      ["Which horse race is known as 'The Sport of Kings' premier event in England, run at Epsom?", "The Derby", "Grand National", "Royal Ascot Gold Cup", "St Leger"],
      ["In which year did Roger Bannister break the 4-minute mile?", "1954", "1948", "1960", "1952"],
      ["Which nation invented the sport of judo?", "Japan", "China", "Korea", "Mongolia"],
      ["How long is an Olympic swimming pool?", "50 meters", "25 meters", "100 meters", "75 meters"],
    ],
  },

  movies: {
    name: "Movies & TV",
    icon: "🎬",
    easy: [
      ["Which movie features the song 'Let It Go'?", "Frozen", "Moana", "Tangled", "Encanto"],
      ["Who is the main character in the Harry Potter films?", "Harry Potter", "Ron Weasley", "Hermione Granger", "Draco Malfoy"],
      ["What kind of animal is Simba in The Lion King?", "Lion", "Tiger", "Leopard", "Cheetah"],
      ["Which superhero is known as the 'Man of Steel'?", "Superman", "Batman", "Iron Man", "Thor"],
      ["In Finding Nemo, what type of fish is Nemo?", "Clownfish", "Angelfish", "Pufferfish", "Goldfish"],
      ["Which movie franchise features Luke Skywalker?", "Star Wars", "Star Trek", "Dune", "Guardians of the Galaxy"],
      ["Who played Jack in Titanic (1997)?", "Leonardo DiCaprio", "Brad Pitt", "Johnny Depp", "Tom Cruise"],
      ["What is the name of the cowboy in Toy Story?", "Woody", "Buzz", "Rex", "Slinky"],
    ],
    medium: [
      ["Which film won the Academy Award for Best Picture in 2020?", "Parasite", "1917", "Joker", "Once Upon a Time in Hollywood"],
      ["Who directed Jurassic Park (1993)?", "Steven Spielberg", "James Cameron", "George Lucas", "Ridley Scott"],
      ["In The Matrix, does Neo take the red or blue pill?", "Red", "Blue", "Green", "Yellow"],
      ["Which actor played the Joker in The Dark Knight (2008)?", "Heath Ledger", "Joaquin Phoenix", "Jack Nicholson", "Jared Leto"],
      ["What is the highest-grossing film of all time (unadjusted, as of 2024)?", "Avatar", "Avengers: Endgame", "Titanic", "Star Wars: The Force Awakens"],
      ["Which TV series features the Iron Throne?", "Game of Thrones", "The Witcher", "Vikings", "The Last Kingdom"],
      ["Who played Forrest Gump?", "Tom Hanks", "Tom Cruise", "Kevin Costner", "Robin Williams"],
      ["Which Indian film won the Oscar for Best Original Song with 'Naatu Naatu'?", "RRR", "Baahubali", "Lagaan", "Slumdog Millionaire"],
    ],
    hard: [
      ["Which film is the only one to feature both a Best Actor and Best Actress Oscar win for its leads — 'It Happened One Night' achieved what rare feat?", "Won all Big Five Oscars", "First color film to win", "First sequel to win", "Longest film to win"],
      ["Who composed the score for Interstellar?", "Hans Zimmer", "John Williams", "Ennio Morricone", "Howard Shore"],
      ["Which 1957 Kurosawa film is an adaptation of Macbeth?", "Throne of Blood", "Ran", "Rashomon", "Yojimbo"],
      ["What was Alfred Hitchcock's first color film?", "Rope", "Vertigo", "Psycho", "Rear Window"],
      ["Which actor has won the most acting Oscars (4)?", "Katharine Hepburn", "Meryl Streep", "Daniel Day-Lewis", "Jack Nicholson"],
      ["Satyajit Ray's Apu Trilogy begins with which film?", "Pather Panchali", "Aparajito", "Apur Sansar", "Charulata"],
      ["What is the name of the fictional metal in Black Panther's Wakanda?", "Vibranium", "Adamantium", "Unobtainium", "Kryptonite"],
      ["Which film holds the record for most Oscar wins (11), tied with Ben-Hur and Titanic?", "The Lord of the Rings: The Return of the King", "Gone with the Wind", "West Side Story", "La La Land"],
    ],
  },

  music: {
    name: "Music",
    icon: "🎵",
    easy: [
      ["How many strings does a standard guitar have?", "6", "4", "5", "7"],
      ["Which instrument has black and white keys?", "Piano", "Violin", "Flute", "Drum"],
      ["Who is known as the 'King of Pop'?", "Michael Jackson", "Elvis Presley", "Prince", "Freddie Mercury"],
      ["Which band sang 'Hey Jude'?", "The Beatles", "The Rolling Stones", "Queen", "ABBA"],
      ["What are the five lines music is written on called?", "Staff", "Scale", "Chord", "Clef"],
      ["Taylor Swift is primarily known as a singer of which genre originally?", "Country", "Rock", "Jazz", "Classical"],
      ["Which instrument does a drummer play?", "Drums", "Guitar", "Trumpet", "Cello"],
      ["The song 'Bohemian Rhapsody' is by which band?", "Queen", "Led Zeppelin", "Pink Floyd", "The Who"],
    ],
    medium: [
      ["Which composer wrote the 'Moonlight Sonata'?", "Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Frédéric Chopin", "Johann Sebastian Bach"],
      ["How many symphonies did Beethoven complete?", "9", "5", "7", "12"],
      ["Which artist released the album 'Thriller'?", "Michael Jackson", "Prince", "Madonna", "Whitney Houston"],
      ["What does 'forte' mean in music?", "Loud", "Soft", "Fast", "Slow"],
      ["Which country did ABBA come from?", "Sweden", "Norway", "Denmark", "Finland"],
      ["A. R. Rahman won two Oscars for the music of which film?", "Slumdog Millionaire", "Life of Pi", "Lagaan", "Gandhi"],
      ["Which rock band performed 'Stairway to Heaven'?", "Led Zeppelin", "Deep Purple", "Aerosmith", "Black Sabbath"],
      ["What is the highest female singing voice?", "Soprano", "Alto", "Mezzo-soprano", "Contralto"],
    ],
    hard: [
      ["Which opera by Puccini features the aria 'Nessun Dorma'?", "Turandot", "La Bohème", "Tosca", "Madama Butterfly"],
      ["What time signature is a waltz typically written in?", "3/4", "4/4", "2/4", "6/8"],
      ["Which jazz trumpeter recorded 'Kind of Blue'?", "Miles Davis", "Louis Armstrong", "Dizzy Gillespie", "Chet Baker"],
      ["Antonio Vivaldi's 'The Four Seasons' is a set of what?", "Violin concertos", "Symphonies", "Operas", "Piano sonatas"],
      ["Which Indian classical instrument did Ravi Shankar famously play?", "Sitar", "Tabla", "Sarod", "Veena"],
      ["Which band's original name was 'The Quarrymen'?", "The Beatles", "The Kinks", "The Hollies", "The Animals"],
      ["What is the term for gradually getting louder in music?", "Crescendo", "Diminuendo", "Staccato", "Legato"],
      ["Who composed the opera 'The Magic Flute'?", "Wolfgang Amadeus Mozart", "Giuseppe Verdi", "Richard Wagner", "Gioachino Rossini"],
    ],
  },

  tech: {
    name: "Technology & Computers",
    icon: "💻",
    easy: [
      ["What does 'WWW' stand for?", "World Wide Web", "World Web Window", "Wide World Web", "Web World Wide"],
      ["Which company makes the iPhone?", "Apple", "Samsung", "Google", "Microsoft"],
      ["What does 'PC' stand for?", "Personal Computer", "Private Computer", "Public Computer", "Portable Computer"],
      ["Which social network is known for 280-character posts?", "Twitter/X", "Facebook", "Instagram", "LinkedIn"],
      ["What is the name of Google's mobile operating system?", "Android", "iOS", "Windows Phone", "Symbian"],
      ["What device do you use to move the cursor on a screen?", "Mouse", "Keyboard", "Printer", "Scanner"],
      ["Which company created Windows?", "Microsoft", "Apple", "IBM", "Intel"],
      ["What does 'USB' stand for?", "Universal Serial Bus", "United Serial Bus", "Universal System Bus", "Unified Serial Base"],
    ],
    medium: [
      ["Who co-founded Apple along with Steve Jobs and Ronald Wayne?", "Steve Wozniak", "Bill Gates", "Elon Musk", "Larry Page"],
      ["What does 'HTML' stand for?", "HyperText Markup Language", "HighText Machine Language", "Hyperlink Text Mode Language", "Home Tool Markup Language"],
      ["Which programming language is named after a snake?", "Python", "Cobra", "Viper", "Anaconda"],
      ["What year was YouTube founded?", "2005", "2003", "2007", "2001"],
      ["What does 'CPU' stand for?", "Central Processing Unit", "Computer Processing Unit", "Central Program Unit", "Core Processing Unit"],
      ["Which company owns Android?", "Google", "Apple", "Samsung", "Nokia"],
      ["What is the binary equivalent of the decimal number 10?", "1010", "1100", "1001", "1110"],
      ["Which company's motto was 'Don't be evil'?", "Google", "Facebook", "Microsoft", "Amazon"],
    ],
    hard: [
      ["Who is considered the father of computer science and broke the Enigma code?", "Alan Turing", "Charles Babbage", "John von Neumann", "Claude Shannon"],
      ["What was the name of the first electronic general-purpose computer?", "ENIAC", "UNIVAC", "Colossus", "EDVAC"],
      ["Which data structure operates on a Last-In-First-Out basis?", "Stack", "Queue", "Linked list", "Heap"],
      ["Who wrote the first computer algorithm, in the 1840s?", "Ada Lovelace", "Grace Hopper", "Charles Babbage", "George Boole"],
      ["What does 'HTTP' status code 404 mean?", "Not Found", "Server Error", "Forbidden", "Bad Gateway"],
      ["Which language was created by Dennis Ritchie at Bell Labs?", "C", "Java", "Fortran", "Pascal"],
      ["What is the name of the first widely used web browser, released in 1993?", "Mosaic", "Netscape Navigator", "Internet Explorer", "Lynx"],
      ["In cryptography, what does 'RSA' derive its name from?", "Its inventors' surnames", "Random Secure Algorithm", "Rapid Security Access", "A government agency"],
    ],
  },

  literature: {
    name: "Literature & Books",
    icon: "📚",
    easy: [
      ["Who wrote 'Romeo and Juliet'?", "William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain"],
      ["What is the name of the wizard school in Harry Potter?", "Hogwarts", "Durmstrang", "Beauxbatons", "Ilvermorny"],
      ["Who wrote 'The Jungle Book'?", "Rudyard Kipling", "Lewis Carroll", "Roald Dahl", "J.M. Barrie"],
      ["In 'Alice in Wonderland', what animal is always late?", "White Rabbit", "Cheshire Cat", "March Hare", "Dormouse"],
      ["Which fairy tale character leaves a glass slipper behind?", "Cinderella", "Snow White", "Rapunzel", "Sleeping Beauty"],
      ["Who created the detective Sherlock Holmes?", "Arthur Conan Doyle", "Agatha Christie", "Edgar Allan Poe", "Raymond Chandler"],
      ["What kind of animal is Charlotte in 'Charlotte's Web'?", "Spider", "Pig", "Goose", "Rat"],
      ["Who wrote 'Matilda' and 'Charlie and the Chocolate Factory'?", "Roald Dahl", "Dr. Seuss", "Enid Blyton", "C.S. Lewis"],
    ],
    medium: [
      ["Who wrote '1984' and 'Animal Farm'?", "George Orwell", "Aldous Huxley", "Ray Bradbury", "H.G. Wells"],
      ["Which novel begins with 'It was the best of times, it was the worst of times'?", "A Tale of Two Cities", "Great Expectations", "Oliver Twist", "David Copperfield"],
      ["Who wrote 'Pride and Prejudice'?", "Jane Austen", "Charlotte Brontë", "Emily Brontë", "Mary Shelley"],
      ["What is the first book of the Old Testament?", "Genesis", "Exodus", "Leviticus", "Numbers"],
      ["Who wrote 'The Old Man and the Sea'?", "Ernest Hemingway", "John Steinbeck", "F. Scott Fitzgerald", "William Faulkner"],
      ["Rabindranath Tagore won the Nobel Prize for which work?", "Gitanjali", "Gora", "The Home and the World", "Kabuliwala"],
      ["In 'Moby-Dick', what is Captain Ahab hunting?", "A white whale", "A giant squid", "A shark", "A sea serpent"],
      ["Who wrote the fantasy series 'A Song of Ice and Fire'?", "George R.R. Martin", "J.R.R. Tolkien", "Brandon Sanderson", "Robert Jordan"],
    ],
    hard: [
      ["Who wrote 'One Hundred Years of Solitude'?", "Gabriel García Márquez", "Jorge Luis Borges", "Mario Vargas Llosa", "Pablo Neruda"],
      ["Which epic poem by Homer tells of Odysseus's journey home?", "The Odyssey", "The Iliad", "The Aeneid", "Metamorphoses"],
      ["Who was the first author to win the Booker Prize twice?", "J.M. Coetzee", "Salman Rushdie", "Hilary Mantel", "Peter Carey"],
      ["'War and Peace' was written by which Russian author?", "Leo Tolstoy", "Fyodor Dostoevsky", "Anton Chekhov", "Ivan Turgenev"],
      ["What is the ancient Indian epic attributed to sage Vyasa?", "Mahabharata", "Ramayana", "Rig Veda", "Upanishads"],
      ["Which dystopian novel features the drug 'soma'?", "Brave New World", "1984", "Fahrenheit 451", "We"],
      ["Who wrote 'The Divine Comedy'?", "Dante Alighieri", "Petrarch", "Boccaccio", "Virgil"],
      ["Which Shakespeare play features the characters Rosencrantz and Guildenstern?", "Hamlet", "Macbeth", "King Lear", "Othello"],
    ],
  },

  math: {
    name: "Mathematics",
    icon: "🔢",
    easy: [
      ["What is 7 × 8?", "56", "54", "48", "64"],
      ["How many sides does a triangle have?", "3", "4", "5", "6"],
      ["What is half of 100?", "50", "25", "40", "60"],
      ["What is the next prime number after 7?", "11", "9", "10", "13"],
      ["How many degrees are in a right angle?", "90", "45", "180", "60"],
      ["What is 12 + 15?", "27", "25", "28", "26"],
      ["What shape has four equal sides and four right angles?", "Square", "Rectangle", "Rhombus", "Trapezoid"],
      ["What is 100 ÷ 4?", "25", "20", "24", "30"],
    ],
    medium: [
      ["What is the value of pi to two decimal places?", "3.14", "3.16", "3.12", "3.18"],
      ["What is the square root of 144?", "12", "14", "11", "13"],
      ["How many degrees do the angles of a triangle add up to?", "180", "360", "90", "270"],
      ["What is 15% of 200?", "30", "25", "35", "40"],
      ["In the Fibonacci sequence 1, 1, 2, 3, 5, what comes next?", "8", "7", "9", "10"],
      ["What is 2 to the power of 10?", "1024", "512", "2048", "100"],
      ["What is the name for a polygon with eight sides?", "Octagon", "Hexagon", "Heptagon", "Nonagon"],
      ["If x + 5 = 12, what is x?", "7", "6", "8", "17"],
    ],
    hard: [
      ["What is the only even prime number?", "2", "0", "4", "6"],
      ["What is the derivative of x²?", "2x", "x", "x²", "2"],
      ["Which mathematician proved Fermat's Last Theorem in 1994?", "Andrew Wiles", "Terence Tao", "Grigori Perelman", "John Nash"],
      ["What is the sum of the interior angles of a hexagon?", "720°", "540°", "900°", "1080°"],
      ["What is 'e' (Euler's number) to two decimal places?", "2.72", "2.68", "3.14", "1.62"],
      ["A number that equals the sum of its proper divisors is called what?", "Perfect number", "Prime number", "Composite number", "Triangular number"],
      ["What is the probability of rolling a sum of 7 with two dice?", "1/6", "1/12", "1/8", "1/9"],
      ["Which Indian mathematician is known for contributions to infinite series and worked with G.H. Hardy?", "Srinivasa Ramanujan", "Aryabhata", "Brahmagupta", "Bhaskara II"],
    ],
  },

  business: {
    name: "Business & Brands",
    icon: "💼",
    easy: [
      ["Which company's logo is a bitten apple?", "Apple", "Samsung", "HP", "Dell"],
      ["Which fast-food chain is famous for golden arches?", "McDonald's", "Burger King", "KFC", "Subway"],
      ["Which company makes the PlayStation?", "Sony", "Microsoft", "Nintendo", "Sega"],
      ["'Just Do It' is the slogan of which brand?", "Nike", "Adidas", "Puma", "Reebok"],
      ["Which coffee chain has a green mermaid logo?", "Starbucks", "Costa Coffee", "Dunkin'", "Café Coffee Day"],
      ["Amazon was founded by whom?", "Jeff Bezos", "Elon Musk", "Bill Gates", "Mark Zuckerberg"],
      ["Which company is famous for the search engine at google.com?", "Google", "Yahoo", "Bing", "DuckDuckGo"],
      ["Tesla is best known for making what?", "Electric cars", "Smartphones", "Aircraft", "Solar ovens"],
    ],
    medium: [
      ["The Tata Group was founded by whom?", "Jamsetji Tata", "J.R.D. Tata", "Ratan Tata", "Dorabji Tata"],
      ["Which stock index tracks 30 large US companies?", "Dow Jones Industrial Average", "S&P 500", "NASDAQ 100", "Russell 2000"],
      ["'Finger Lickin' Good' is the slogan of which brand?", "KFC", "McDonald's", "Pizza Hut", "Domino's"],
      ["Which Swedish company is famous for flat-pack furniture?", "IKEA", "H&M", "Electrolux", "Volvo"],
      ["What does 'IPO' stand for?", "Initial Public Offering", "International Purchase Order", "Internal Profit Objective", "Initial Private Offering"],
      ["Which Indian company is the largest IT services firm by market cap (as of 2024)?", "TCS", "Infosys", "Wipro", "HCLTech"],
      ["Which luxury brand uses the interlocking 'CC' logo?", "Chanel", "Gucci", "Louis Vuitton", "Prada"],
      ["Which company acquired WhatsApp in 2014?", "Facebook (Meta)", "Google", "Microsoft", "Twitter"],
    ],
    hard: [
      ["Which company was originally called 'BackRub'?", "Google", "Yahoo", "Amazon", "eBay"],
      ["Who is known as the father of modern management?", "Peter Drucker", "Philip Kotler", "Michael Porter", "Jack Welch"],
      ["Nokia originally started as what kind of company?", "Paper mill", "Telephone maker", "Rubber factory", "Electronics shop"],
      ["Which Indian conglomerate owns Jaguar Land Rover?", "Tata Motors", "Mahindra", "Reliance", "Adani Group"],
      ["The 'Tata Crucible' is a famous corporate event of what kind?", "Business quiz competition", "Marathon", "Hackathon", "Debate contest"],
      ["Which economist wrote 'The Wealth of Nations'?", "Adam Smith", "John Maynard Keynes", "Karl Marx", "Milton Friedman"],
      ["What was the first company to reach a $1 trillion market cap?", "Apple", "Amazon", "Microsoft", "PetroChina"],
      ["Which Japanese term meaning 'continuous improvement' is used in business?", "Kaizen", "Kanban", "Ikigai", "Keiretsu"],
    ],
  },

  india: {
    name: "India",
    icon: "🇮🇳",
    easy: [
      ["What is the capital of India?", "New Delhi", "Mumbai", "Kolkata", "Chennai"],
      ["Which is the national animal of India?", "Bengal Tiger", "Lion", "Elephant", "Peacock"],
      ["The Taj Mahal is located in which city?", "Agra", "Delhi", "Jaipur", "Lucknow"],
      ["Who is known as the 'Father of the Nation' in India?", "Mahatma Gandhi", "Jawaharlal Nehru", "Sardar Patel", "B.R. Ambedkar"],
      ["Which festival is known as the 'Festival of Lights'?", "Diwali", "Holi", "Eid", "Navratri"],
      ["What is the national bird of India?", "Peacock", "Parrot", "Eagle", "Swan"],
      ["Which river is considered the holiest in India?", "Ganga", "Yamuna", "Godavari", "Krishna"],
      ["In which year did India gain independence?", "1947", "1950", "1942", "1945"],
    ],
    medium: [
      ["Who was the first Prime Minister of India?", "Jawaharlal Nehru", "Mahatma Gandhi", "Sardar Patel", "Rajendra Prasad"],
      ["Which Indian state is known as the 'Land of Five Rivers'?", "Punjab", "Haryana", "Rajasthan", "Gujarat"],
      ["Who wrote the Indian national anthem?", "Rabindranath Tagore", "Bankim Chandra Chatterjee", "Sarojini Naidu", "Subramania Bharati"],
      ["Which city is known as the 'Silicon Valley of India'?", "Bengaluru", "Hyderabad", "Pune", "Chennai"],
      ["The Konark Sun Temple is in which state?", "Odisha", "West Bengal", "Tamil Nadu", "Karnataka"],
      ["Who was the first Indian to win an individual Olympic gold medal?", "Abhinav Bindra", "Neeraj Chopra", "Milkha Singh", "P.T. Usha"],
      ["Which Indian space mission reached Mars orbit in 2014?", "Mangalyaan", "Chandrayaan-1", "Gaganyaan", "Aditya-L1"],
      ["What is the currency of India?", "Rupee", "Taka", "Rupiah", "Dinar"],
    ],
    hard: [
      ["Who founded the Maurya Empire?", "Chandragupta Maurya", "Ashoka", "Bindusara", "Chanakya"],
      ["The Ajanta and Ellora caves are in which state?", "Maharashtra", "Madhya Pradesh", "Karnataka", "Telangana"],
      ["Who was the first woman President of India?", "Pratibha Patil", "Indira Gandhi", "Sarojini Naidu", "Droupadi Murmu"],
      ["Which Article of the Indian Constitution deals with the Right to Equality?", "Article 14", "Article 21", "Article 19", "Article 32"],
      ["The ancient university of Nalanda was located in present-day which state?", "Bihar", "Uttar Pradesh", "West Bengal", "Odisha"],
      ["Who composed the song 'Vande Mataram'?", "Bankim Chandra Chatterjee", "Rabindranath Tagore", "Sarojini Naidu", "Muhammad Iqbal"],
      ["Which Indian physicist won the Nobel Prize in 1930 for light scattering?", "C.V. Raman", "Homi Bhabha", "S. Chandrasekhar", "Satyendra Nath Bose"],
      ["The Battle of Plassey (1757) was fought in present-day which state?", "West Bengal", "Bihar", "Odisha", "Uttar Pradesh"],
    ],
  },

  food: {
    name: "Food & Drink",
    icon: "🍜",
    easy: [
      ["Which fruit is known for keeping the doctor away?", "Apple", "Banana", "Orange", "Grape"],
      ["What is sushi traditionally wrapped in?", "Seaweed", "Lettuce", "Rice paper", "Banana leaf"],
      ["Which country is famous for pizza and pasta?", "Italy", "France", "Spain", "Greece"],
      ["What is the main ingredient in guacamole?", "Avocado", "Tomato", "Cucumber", "Pepper"],
      ["Which drink is made from fermented grapes?", "Wine", "Beer", "Whiskey", "Vodka"],
      ["What type of food is a baguette?", "Bread", "Cheese", "Pastry", "Sausage"],
      ["Honey is made by which insects?", "Bees", "Ants", "Wasps", "Butterflies"],
      ["Which vegetable is used to make french fries?", "Potato", "Carrot", "Turnip", "Beetroot"],
    ],
    medium: [
      ["Which spice is the most expensive by weight?", "Saffron", "Vanilla", "Cardamom", "Cinnamon"],
      ["What is the main ingredient of hummus?", "Chickpeas", "Lentils", "Beans", "Peas"],
      ["Which country is the origin of the dish paella?", "Spain", "Portugal", "Mexico", "Italy"],
      ["What cheese is traditionally used on a Margherita pizza?", "Mozzarella", "Cheddar", "Parmesan", "Gouda"],
      ["Which nation drinks the most tea per capita?", "Turkey", "England", "India", "China"],
      ["Masala dosa originated in which part of India?", "South India", "North India", "East India", "West India"],
      ["What is Japanese sake made from?", "Rice", "Wheat", "Barley", "Corn"],
      ["Which fruit is the base for traditional Indian mango lassi?", "Mango", "Papaya", "Banana", "Guava"],
    ],
    hard: [
      ["What is the world's most stolen food?", "Cheese", "Chocolate", "Meat", "Coffee"],
      ["Which pepper is used to measure the Scoville scale's origins?", "Chili pepper heat", "Black pepper weight", "Bell pepper size", "Paprika color"],
      ["What is the traditional Japanese soup base made from fish and kelp?", "Dashi", "Miso", "Ramen", "Ponzu"],
      ["'Umami' — the fifth taste — was identified by a scientist from which country?", "Japan", "China", "France", "Germany"],
      ["Which French term means 'everything in its place' in cooking?", "Mise en place", "Sous vide", "Au gratin", "En papillote"],
      ["What is the world's most expensive coffee, partly digested by civets?", "Kopi Luwak", "Blue Mountain", "Death Wish", "Geisha"],
      ["Which country produces the most cocoa beans?", "Ivory Coast", "Ghana", "Brazil", "Ecuador"],
      ["Biryani is believed to have been brought to India by which influence?", "Mughal/Persian", "Portuguese", "British", "Chinese"],
    ],
  },

  mythology: {
    name: "Mythology & Beliefs",
    icon: "⚡",
    easy: [
      ["Who is the Greek god of the sea?", "Poseidon", "Zeus", "Hades", "Apollo"],
      ["Thor, the god of thunder, comes from which mythology?", "Norse", "Greek", "Egyptian", "Roman"],
      ["Who is the king of the Greek gods?", "Zeus", "Poseidon", "Ares", "Hermes"],
      ["Which creature in Greek myth has snakes for hair?", "Medusa", "Sphinx", "Hydra", "Chimera"],
      ["In Hindu mythology, who is the elephant-headed god?", "Ganesha", "Hanuman", "Shiva", "Krishna"],
      ["What winged horse appears in Greek mythology?", "Pegasus", "Unicorn", "Griffin", "Centaur"],
      ["Which Roman god is the god of war?", "Mars", "Jupiter", "Neptune", "Mercury"],
      ["Who flew too close to the sun with wax wings?", "Icarus", "Daedalus", "Perseus", "Theseus"],
    ],
    medium: [
      ["Who is the Egyptian god of the afterlife?", "Osiris", "Ra", "Anubis", "Horus"],
      ["In Norse mythology, what is the name of Odin's eight-legged horse?", "Sleipnir", "Fenrir", "Jormungandr", "Gullinbursti"],
      ["Which hero completed the Twelve Labors in Greek myth?", "Heracles", "Achilles", "Odysseus", "Jason"],
      ["In the Ramayana, who kidnapped Sita?", "Ravana", "Kumbhakarna", "Indrajit", "Vibhishana"],
      ["What is the Norse end-of-world event called?", "Ragnarok", "Valhalla", "Yggdrasil", "Bifrost"],
      ["Who is the Greek goddess of wisdom?", "Athena", "Hera", "Aphrodite", "Artemis"],
      ["Which bird rises from its own ashes in mythology?", "Phoenix", "Roc", "Thunderbird", "Garuda"],
      ["In Hindu mythology, what is the vehicle (vahana) of Lord Vishnu?", "Garuda", "Nandi", "Peacock", "Mouse"],
    ],
    hard: [
      ["Who is the Norse goddess associated with love and war, receiving half the battle-slain?", "Freyja", "Frigg", "Sif", "Hel"],
      ["In Greek myth, who was condemned to roll a boulder uphill forever?", "Sisyphus", "Tantalus", "Prometheus", "Atlas"],
      ["What is the name of the Mesopotamian epic hero who sought immortality?", "Gilgamesh", "Enkidu", "Marduk", "Hammurabi"],
      ["In Egyptian myth, whose heart is weighed against the feather of Ma'at?", "The deceased's", "The pharaoh's", "Anubis's", "Ra's"],
      ["Which weapon does Lord Indra wield in Hindu mythology?", "Vajra (thunderbolt)", "Trishula", "Sudarshana Chakra", "Gada"],
      ["Who is the Japanese sun goddess?", "Amaterasu", "Izanami", "Tsukuyomi", "Susanoo"],
      ["The Minotaur was kept in a labyrinth on which island?", "Crete", "Rhodes", "Delos", "Ithaca"],
      ["In Aztec mythology, who is the feathered serpent god?", "Quetzalcoatl", "Tezcatlipoca", "Huitzilopochtli", "Tlaloc"],
    ],
  },
};

/* Category keys in display order */
const CATEGORY_KEYS = Object.keys(QUESTION_BANK);
const DIFFICULTIES = ["easy", "medium", "hard"];
